team_number = 4533
ntables_ip = "127.0.0.1"
device_name = "chalkydri3372531970"

[[cameras]]
name = "pipewiredevice0"
display_name = "Integrated_Webcam_HD (V4L2)"

[cameras.subsystems.capriltags]
enabled = true

[cameras.subsystems.capriltags.field_layouts]

[cameras.subsystems.ml]
enabled = false
