team_number = 4533
ntables_ip = "192.168.0.211"
device_name = "chalkydri3372531970"

[[cameras]]
name = "pipewiredevice0"
display_name = "Integrated_Webcam_HD (V4L2)"

[cameras.settings]
width = 1280
height = 720

[cameras.settings.frame_rate]
num = 30
den = 1

[subsystems.capriltags]
enabled = true

[subsystems.ml]
enabled = false
