team_number = 4533
ntables_ip = "127.0.0.1"
device_name = "chalkydri3372531970"

[[cameras]]
name = "pipewiredevice0"
display_name = "Integrated_Webcam_HD (V4L2)"

[cameras.settings]
width = 1280
height = 720

[cameras.settings.frame_rate]
num = 30
den = 1

[cameras.subsystems.capriltags]
enabled = true
field_layout = "layout.json"

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 1

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 16.697198
y = 0.65532
z = 1.4859

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.4539904997395468
X = 0.0
Y = 0.0
Z = 0.8910065241883678

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 2

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 16.697198
y = 7.39648
z = 1.4859

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.4539904997395467
X = 0.0
Y = 0.0
Z = 0.8910065241883679

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 3

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 11.560809999999998
y = 8.05561
z = 1.30175

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.7071067811865475
X = 0.0
Y = 0.0
Z = 0.7071067811865476

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 4

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 9.27608
y = 6.137656
z = 1.867916

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.9659258262890684
X = 0.0
Y = 0.25881904510252074
Z = 0.0

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 5

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 9.27608
y = 1.914906
z = 1.867916

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.9659258262890684
X = 0.0
Y = 0.25881904510252074
Z = 0.0

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 6

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 13.474446
y = 3.3063179999999996
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.8660254037844387
X = 0.0
Y = 0.0
Z = 0.49999999999999994

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 7

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 13.890498
y = 4.0259
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 1.0
X = 0.0
Y = 0.0
Z = 0.0

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 8

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 13.474446
y = 4.745482
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.8660254037844387
X = 0.0
Y = 0.0
Z = 0.49999999999999994

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 9

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 12.643358
y = 4.745482
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.5000000000000001
X = 0.0
Y = 0.0
Z = 0.8660254037844386

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 10

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 12.227306
y = 4.0259
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.00000000000000006123233995736766
X = 0.0
Y = 0.0
Z = 1.0

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 11

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 12.643358
y = 3.3063179999999996
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.4999999999999998
X = 0.0
Y = 0.0
Z = 0.8660254037844387

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 12

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 0.851154
y = 0.65532
z = 1.4859

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.8910065241883679
X = 0.0
Y = 0.0
Z = 0.4539904997395467

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 13

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 0.851154
y = 7.39648
z = 1.4859

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.8910065241883678
X = 0.0
Y = 0.0
Z = 0.45399049973954686

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 14

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 8.272272
y = 6.137656
z = 1.867916

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.00000000000000005914589856893349
X = -0.25881904510252074
Y = 0.000000000000000015848095757158825
Z = 0.9659258262890684

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 15

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 8.272272
y = 1.914906
z = 1.867916

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.00000000000000005914589856893349
X = -0.25881904510252074
Y = 0.000000000000000015848095757158825
Z = 0.9659258262890684

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 16

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 5.9875419999999995
y = -0.00381
z = 1.30175

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.7071067811865476
X = 0.0
Y = 0.0
Z = 0.7071067811865476

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 17

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 4.073905999999999
y = 3.3063179999999996
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.4999999999999998
X = 0.0
Y = 0.0
Z = 0.8660254037844387

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 18

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 3.6576
y = 4.0259
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.00000000000000006123233995736766
X = 0.0
Y = 0.0
Z = 1.0

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 19

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 4.073905999999999
y = 4.745482
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.5000000000000001
X = 0.0
Y = 0.0
Z = 0.8660254037844386

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 20

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 4.904739999999999
y = 4.745482
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.8660254037844387
X = 0.0
Y = 0.0
Z = 0.49999999999999994

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 21

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 5.321046
y = 4.0259
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 1.0
X = 0.0
Y = 0.0
Z = 0.0

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 22

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 4.904739999999999
y = 3.3063179999999996
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.8660254037844387
X = 0.0
Y = 0.0
Z = 0.49999999999999994

[cameras.subsystems.capriltags.field_layouts."layout.json".field]
length = 17.548
width = 8.052

[cameras.subsystems.ml]
enabled = false

[[cameras]]
name = "pipewiredevice2"
display_name = "Microsoft® LifeCam HD-3000 (V4L2)"

[cameras.settings]
width = 1280
height = 720

[cameras.settings.frame_rate]
num = 30
den = 1

[cameras.subsystems.capriltags]
enabled = true
field_layout = "layout.json"

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 1

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 16.697198
y = 0.65532
z = 1.4859

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.4539904997395468
X = 0.0
Y = 0.0
Z = 0.8910065241883678

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 2

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 16.697198
y = 7.39648
z = 1.4859

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.4539904997395467
X = 0.0
Y = 0.0
Z = 0.8910065241883679

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 3

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 11.560809999999998
y = 8.05561
z = 1.30175

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.7071067811865475
X = 0.0
Y = 0.0
Z = 0.7071067811865476

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 4

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 9.27608
y = 6.137656
z = 1.867916

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.9659258262890684
X = 0.0
Y = 0.25881904510252074
Z = 0.0

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 5

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 9.27608
y = 1.914906
z = 1.867916

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.9659258262890684
X = 0.0
Y = 0.25881904510252074
Z = 0.0

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 6

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 13.474446
y = 3.3063179999999996
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.8660254037844387
X = 0.0
Y = 0.0
Z = 0.49999999999999994

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 7

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 13.890498
y = 4.0259
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 1.0
X = 0.0
Y = 0.0
Z = 0.0

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 8

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 13.474446
y = 4.745482
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.8660254037844387
X = 0.0
Y = 0.0
Z = 0.49999999999999994

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 9

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 12.643358
y = 4.745482
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.5000000000000001
X = 0.0
Y = 0.0
Z = 0.8660254037844386

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 10

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 12.227306
y = 4.0259
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.00000000000000006123233995736766
X = 0.0
Y = 0.0
Z = 1.0

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 11

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 12.643358
y = 3.3063179999999996
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.4999999999999998
X = 0.0
Y = 0.0
Z = 0.8660254037844387

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 12

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 0.851154
y = 0.65532
z = 1.4859

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.8910065241883679
X = 0.0
Y = 0.0
Z = 0.4539904997395467

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 13

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 0.851154
y = 7.39648
z = 1.4859

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.8910065241883678
X = 0.0
Y = 0.0
Z = 0.45399049973954686

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 14

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 8.272272
y = 6.137656
z = 1.867916

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.00000000000000005914589856893349
X = -0.25881904510252074
Y = 0.000000000000000015848095757158825
Z = 0.9659258262890684

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 15

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 8.272272
y = 1.914906
z = 1.867916

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.00000000000000005914589856893349
X = -0.25881904510252074
Y = 0.000000000000000015848095757158825
Z = 0.9659258262890684

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 16

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 5.9875419999999995
y = -0.00381
z = 1.30175

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.7071067811865476
X = 0.0
Y = 0.0
Z = 0.7071067811865476

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 17

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 4.073905999999999
y = 3.3063179999999996
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.4999999999999998
X = 0.0
Y = 0.0
Z = 0.8660254037844387

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 18

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 3.6576
y = 4.0259
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.00000000000000006123233995736766
X = 0.0
Y = 0.0
Z = 1.0

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 19

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 4.073905999999999
y = 4.745482
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.5000000000000001
X = 0.0
Y = 0.0
Z = 0.8660254037844386

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 20

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 4.904739999999999
y = 4.745482
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 0.8660254037844387
X = 0.0
Y = 0.0
Z = 0.49999999999999994

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 21

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 5.321046
y = 4.0259
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = 1.0
X = 0.0
Y = 0.0
Z = 0.0

[[cameras.subsystems.capriltags.field_layouts."layout.json".tags]]
ID = 22

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.translation]
x = 4.904739999999999
y = 3.3063179999999996
z = 0.308102

[cameras.subsystems.capriltags.field_layouts."layout.json".tags.pose.rotation.quaternion]
W = -0.8660254037844387
X = 0.0
Y = 0.0
Z = 0.49999999999999994

[cameras.subsystems.capriltags.field_layouts."layout.json".field]
length = 17.548
width = 8.052

[cameras.subsystems.ml]
enabled = false
