team_number = 4533
device_name = "chalkydri3372531970"

[[cameras]]
name = "pipewiredevice0"
display_name = "Integrated_Webcam_HD (V4L2)"

[cameras.subsystems.capriltags]
enabled = false

[cameras.subsystems.capriltags.field_layouts]

[cameras.subsystems.ml]
enabled = false

[[cameras]]
name = "pipewiredevice2"
display_name = "Arducam OV9281 USB Camera (V4L2)"

[cameras.settings]
width = 1280
height = 720

[cameras.settings.frame_rate]
num = 120
den = 1

[cameras.subsystems.capriltags]
enabled = false

[cameras.subsystems.capriltags.field_layouts]

[cameras.subsystems.ml]
enabled = false
