name: Build / test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  actions: read
  statuses: read
  deployments: write
  packages: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/chalkydri/chalkydri:dev
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Restore from cache
        uses: actions/cache/restore@v4
        with:
          key: cargo
          path: |
            ~/.cargo
            ~/.rustup
      
      - name: Install rust nightly
        run: rustup update nightly && rustup default nightly

      - name: Run check
        run: cargo check --workspace --keep-going
      
      - name: Run tests
        run: cargo test --workspace --no-fail-fast
      
      - name: Save to cache
        uses: actions/cache/save@v4
        with:
          key: cargo
          path: |
            ~/.cargo
            ~/.rustup
